# Generated by Django 4.2 on 2023-09-07 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_campaign', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_campaign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(max_length=100, null=True)),
                ('logo_name', models.CharField(blank=True, max_length=100)),
                ('logo_same_for_all', models.BooleanField(default=False, null=True)),
                ('send_art_to_customer', models.BooleanField(null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('proof_request_type', models.CharField(choices=[('1', 'Standard Proof Request'), ('2', 'Apparel Proof Request'), ('3', 'Branded Guideline Request '), ('4', 'Complex Art Request'), ('5', 'Vectorization Logo Request')], default='Standard Proof Request', max_length=100)),
                ('customer_no', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('segment_no', models.CharField(blank=True, max_length=100)),
                ('rep_no', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'New'), ('2', 'In-Progress'), ('3', 'On Hold'), ('4', 'Queries'), ('5', 'Corrections'), ('6', 'Rush Corrections'), ('7', 'Completed'), ('8', 'Cancelled'), ('9', 'Queries Resolved'), ('10', 'Customer Approved'), ('11', 'Final Approved')], default='New', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='job.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_job_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_job_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jobs',
                'verbose_name_plural': 'Job',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Jobitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100)),
                ('product_color', models.CharField(max_length=200, null=True)),
                ('imprint_color', models.CharField(max_length=200, null=True)),
                ('imprint_location', models.CharField(max_length=200, null=True)),
                ('imprint_method', models.CharField(blank=True, max_length=200, null=True)),
                ('imprint_instructions', models.CharField(blank=True, max_length=500, null=True)),
                ('completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_jobitem_user', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='job.job')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_jobitem_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SubmittedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_files', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_files', to='job.jobitem')),
            ],
        ),
        migrations.CreateModel(
            name='LogoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_files', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_files', to='job.jobitem')),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_datetime', models.DateTimeField(auto_now=True)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.CharField(max_length=500)),
                ('log_type', models.CharField(blank=True, max_length=500)),
                ('prev_status', models.CharField(blank=True, max_length=500)),
                ('new_status', models.CharField(blank=True, max_length=500)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_log', to='job.job')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_log_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EpsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps_files', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eps_files', to='job.jobitem')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_files', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_files', to='job.jobitem')),
            ],
        ),
    ]
